# Generated by Django 4.1.1 on 2022-09-30 19:17

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles/images', validators=[main.validators.validate_file_size]),
        ),
    ]
