# Generated by Django 4.1 on 2022-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_name', 'first_name', 'username'], name='main_userpr_last_na_c3be3e_idx'),
        ),
    ]
