# Generated by Django 4.1 on 2022-08-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='servings_avalible',
            new_name='servings_available',
        ),
    ]
