# Generated by Django 4.1.1 on 2022-11-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_id_alter_post_servings_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=34.4691131, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-110.0921453, max_digits=9),
            preserve_default=False,
        ),
    ]
