# Generated by Django 4.1.1 on 2022-12-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_latitude_alter_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='main.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='main.userprofile'),
        ),
    ]
