# Generated by Django 4.1 on 2022-08-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userprofile_main_userpr_last_na_c3be3e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
