# Generated by Django 4.1 on 2022-08-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
    ]
