# Generated by Django 4.1.1 on 2022-09-07 21:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderitem_order_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/images', validators=[main.validators.validate_file_size]),
        ),
    ]
